// [Config Logic] Centralized Configuration for BubbleChat
// You can manually edit this file or overwrite it using the Export function in config.html
// AI Should Not Change Any Mapping that is already present
window.HIVE_SOUND_CONFIG = {
    // [Screen Effects]
    "커플": { "src": "DieWithASmile.mp3", "volume": 0.5 },
    "버질": { "src": "I AM THE STORM.mp3", "volume": 0.5 },
    "돌핀": { "src": "Dolphin.mp3", "volume": 0.5 },
    "하트": { "src": "Heart.mp3", "volume": 0.5 },

    "해골": [
        { "src": "skullmeme.mp3", "volume": 0.5 },
        { "src": "skullmeme2.mp3", "volume": 0.5 },
        { "src": "skullmeme3.mp3", "volume": 0.5 },
        { "src": "skullmeme4.mp3", "volume": 0.5 },
        { "src": "skullmeme6.mp3", "volume": 0.5 },
        { "src": "skullmeme8.mp3", "volume": 0.5 },
        { "src": "skullmeme9.mp3", "volume": 0.5 },
        { "src": "skullmeme10.mp3", "volume": 0.5 },
        { "src": "skullmeme11.mp3", "volume": 0.5 }
    ],
    "앙": { "src": "Ang.mp3", "volume": 0.5 },
    "재밌다": { "src": "Fun.wav", "volume": 0.4 },
    "당근": { "src": "Carrot.mp3", "volume": 0.4 },
    "알림": { "src": "Alarm.mp3", "volume": 0.4 },

    // [Reactions & Memes]
    "ㅋ": { "src": "Laugh1.mp3", "volume": 0.5 },
    "ㅋㅋ": { "src": "Laugh2.mp3", "volume": 0.5 },
    "ㅋㅋㅋ": { "src": "Laugh3.mp3", "volume": 0.6 },
    "ㅋㅋㅋㅋ": { "src": "Laugh6.mp3", "volume": 0.3 },
    "ㅋㅋㅋㅋㅋ": { "src": "Laugh.mp3", "volume": 0.3 },
    "ㅋㅋㅋㅋㅋㅋ": { "src": "Laugh7.mp3", "volume": 0.3 },
    "ㅋㅋㅋㅋㅋㅋㅋ": { "src": "Laugh8.mp3", "volume": 0.5 },
    "ㅋㅋㅋㅋㅋㅋㅋㅋ": { "src": "Laugh4.mp3", "volume": 0.15 },
    "ㅋㅋㅋㅋㅋㅋㅋㅋㅋ": { "src": "Laugh10.mp3", "volume": 0.5 },
    "ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ": { "src": "Laugh5.mp3", "volume": 0.3 },

    "아항항": { "src": "Laugh3.mp3", "volume": 0.6 },
    "와우": { "src": "Wow.mp3", "volume": 0.5 },
    "오옷": { "src": "Ot.wav", "volume": 0.4 },
    "헤으응": { "src": "Careless.mp3", "volume": 0.4 },
    "아흐앙": { "src": "ahng.mp3", "volume": 0.5 },
    "아흐응": { "src": "ah5.mp3", "volume": 0.3 },
    "아흣": { "src": "ah2.mp3", "volume": 0.4 },
    "아하앙": { "src": "ah3.mp3", "volume": 0.4 },
    "하으앙": { "src": "ah4.mp3", "volume": 0.4 },
    "윽": { "src": "ast5.mp3", "volume": 0.5 },
    "야스": { "src": "Yas.mp3", "volume": 0.5 },
    "갓겜": { "src": "godgame.mp3", "volume": 0.5 },
    "두둥탁": { "src": "ddt.mp3", "volume": 0.5 },
    "짜잔": { "src": "tadah.mp3", "volume": 0.45 },
    "???": { "src": "mystery.mp3", "volume": 0.45 },
    "브로": { "src": "Bruh.mp3", "volume": 0.45 },
    "도파민": { "src": "Dopamin.mp3", "volume": 0.45 },
    "FBI": { "src": "FBI.mp3", "volume": 0.5 },
    "으아아": { "src": "Half-falling.mp3", "volume": 0.5 },
    "놉": { "src": "Nope.mp3", "volume": 0.5 },
    "더러워": { "src": "dirty.mp3", "volume": 0.6 },
    "비둘기": { "src": "pigeon.mp3", "volume": 0.5 },
    "야!": { "src": "야.mp3", "volume": 0.5 },
    "와!": [
        { "src": "chant1.mp3", "volume": 0.45 },
        { "src": "chant2.mp3", "volume": 0.5 },
        { "src": "chant3.mp3", "volume": 0.5 }
    ],
    "우와": { "src": "OMG_Good.mp3", "volume": 0.5 },
    "맙소사": { "src": "OMG.mp3", "volume": 0.5 },
    "앙기모띠": { "src": "AngKiMoChi.mp3", "volume": 0.5 },
    "기모띠": { "src": "kimotee.mp3", "volume": 0.5 },
    "응원": [
        { "src": "Cheer.mp3", "volume": 0.5 },
        { "src": "Cheer2.mp3", "volume": 0.5 },
        { "src": "Cheer3.mp3", "volume": 0.5 },
        { "src": "Cheer4.mp3", "volume": 0.5 },
        { "src": "Cheer6.mp3", "volume": 0.5 },
        { "src": "Cheer7.mp3", "volume": 0.5 },
        { "src": "Cheer9.mp3", "volume": 0.5 },
        { "src": "Cheer10.mp3", "volume": 0.5 }
    ],
    "미국맛": { "src": "Disconnected.mp3", "volume": 0.5 },
    "개소리": [
        { "src": "DogShit.mp3", "volume": 0.6 },
        { "src": "DogShit2.mp3", "volume": 0.5 },
        { "src": "DogShit3.mp3", "volume": 0.6 }
    ],
    "두잇": [
        { "src": "Doit1.mp3", "volume": 0.5 },
        { "src": "Doit2.mp3", "volume": 0.5 }
    ],
    "망했": { "src": "Doomed.mp3", "volume": 0.5 },
    "내눈": [
        { "src": "MyEyes01.mp3", "volume": 0.4 },
        { "src": "MyEyes02.mp3", "volume": 0.4 },
        { "src": "MyEyes03.mp3", "volume": 0.4 }
    ],
    "쌍욕": [
        { "src": "Bitch.mp3", "volume": 0.4 },
        { "src": "Fuck.mp3", "volume": 0.4 },
        { "src": "SuchABitch.mp3", "volume": 0.4 }
    ],
    "히히": [
        { "src": "WickedLaugh1.mp3", "volume": 0.7 },
        { "src": "WickedLaugh2.mp3", "volume": 0.7 },
        { "src": "WickedLaugh3.mp3", "volume": 0.7 },
        { "src": "WickedLaugh4.mp3", "volume": 0.7 }
    ],
    "대박": { "src": "Wow10.mp3", "volume": 0.5 },
    "오오오": { "src": "Chant4.mp3", "volume": 0.35 },
    "호우": { "src": "SIU.mp3", "volume": 0.7 },
    "siu": { "src": "SIU.mp3", "volume": 0.7 },
    "끼얏호": { "src": "Yiaho.mp3", "volume": 0.30 },
    "위이": { "src": "Wieeee.mp3", "volume": 0.65 },
    "홋치": { "src": "whip.mp3", "volume": 0.5 },
    "맛있다": { "src": "Mat.mp3", "volume": 0.5 },

    // [Negative / Refusal]
    "안돼": [
        { "src": "no (1).mp3", "volume": 0.5 },
        { "src": "No.mp3", "volume": 1 },
        { "src": "No2.mp3", "volume": 0.5 },
        { "src": "No3.mp3", "volume": 0.5 },
        { "src": "No6.mp3", "volume": 0.5 }
    ],
    "멈춰!": { "src": "Stop.mp3", "volume": 0.65 },
    "꺼져": { "src": "foff.mp3", "volume": 0.45 },
    "뚝": { "src": "DDuk.wav", "volume": 0.4 },
    "쇼크": { "src": "shocked-sound-effect.mp3", "volume": 0.3 },
    "스트레스": { "src": "StressNeeds.mp3", "volume": 0.4 },
    "어림 없": { "src": "NoWay.mp3", "volume": 0.5 },
    "어림없": { "src": "NoWay.mp3", "volume": 0.5 },
    "응 아니야": { "src": "K-Nope.mp3", "volume": 0.5 },
    "죽고 싶지 않": { "src": "Don'tWannaDie.mp3", "volume": 0.5 },
    "장비를 정지": { "src": "Half-Stop.mp3", "volume": 0.5 },
    "너무한": { "src": "TooHarsh.mp3", "volume": 0.65 },
    "안되잖아": { "src": "Half-not-working.mp3", "volume": 0.5 },
    "정지가 안돼": [
        { "src": "Half-not-working2.mp3", "volume": 0.5 },
        { "src": "half-not-working4.mp3", "volume": 0.5 }
    ],

    // [Situation / Alerts]
    "하이": [
        { "src": "Hi1.mp3", "volume": 0.3 },
        { "src": "Hi2.mp3", "volume": 0.3 },
        { "src": "Hi3.mp3", "volume": 0.3 }
    ],
    "안녕하세요": { "src": "Hello1.mp3", "volume": 0.5 },
    "헬로": { "src": "Hello2.mp3", "volume": 1 },
    "바이": { "src": "Bye.mp3", "volume": 0.8 },
    "안녕히": { "src": "FareWellEveryone.mp3", "volume": 0.5 },
    "카톡": { "src": "Katalk.wav", "volume": 0.5 },
    "전화": { "src": "Call.WAV", "volume": 0.5 },
    "보이스콜": { "src": "KakaoCall.mp3", "volume": 0.5 },
    "디코": { "src": "discord.mp3", "volume": 0.5 },
    "잠시후": { "src": "FUmomentsLater.mp3", "volume": 0.7 },
    "장실": { "src": "willBeRightBack.mp3", "volume": 0.35 },
    "부끝": { "src": "willBeRightBack.mp3", "volume": 0.35 },
    "수류탄": { "src": "FireInTheHole.mp3", "volume": 0.5 },
    "탈출": [
        { "src": "Escape.mp3", "volume": 0.5 },
        { "src": "Escape2.mp3", "volume": 0.5 },
        { "src": "Escape3.mp3", "volume": 0.5 },
        { "src": "Escape4.mp3", "volume": 0.5 }
    ],
    "튀어": { "src": "RUN.mp3", "volume": 0.5 },
    "시작": { "src": "Begin.mp3", "volume": 0.5 },
    "가자!": { "src": "LetsGo.mp3", "volume": 0.75 },
    "결제": { "src": "applepay.mp3", "volume": 0.7 },
    "예상대로": { "src": "Predict.mp3", "volume": 0.5 },
    "배운다": { "src": "Learing.mp3", "volume": 0.4 },
    "운동": { "src": "workouthard.mp3", "volume": 0.4 },
    "유격": { "src": "MohyungTower.mp3", "volume": 0.5 },
    "일어나": [
        { "src": "WakeUp1.mp3", "volume": 0.5 },
        { "src": "WakeUp2.mp3", "volume": 0.5 },
        { "src": "WakeUp3.mp3", "volume": 0.5 },
        { "src": "WakeUp4.mp3", "volume": 0.5 },
        { "src": "WakeUp6.mp3", "volume": 0.5 },
        { "src": "WakeUp7.mp3", "volume": 0.5 },
        { "src": "WakeUp8.mp3", "volume": 0.5 },
        { "src": "WakeUp9.mp3", "volume": 0.5 }
    ],
    "뭐임?": { "src": "WTF.mp3", "volume": 0.5 },
    "엥?": { "src": "Huh.mp3", "volume": 0.5 },
    "음?": { "src": "Huh.mp3", "volume": 0.5 },
    "뭣?": { "src": "Huh.mp3", "volume": 0.5 },
    "ㅔ?": { "src": "Huh.mp3", "volume": 0.5 },
    "ㅖ?": { "src": "Huh.mp3", "volume": 0.5 },
    "마인": { "src": "MineMine.mp3", "volume": 0.5 },
    "제꺼": { "src": "NowMine.mp3", "volume": 0.8 },
    "마이!": [
        { "src": "MineMine.mp3", "volume": 0.5 }
    ],
    "마이쩡": { "src": "SoDelicious.mp3", "volume": 0.5 },
    "마이쪙": { "src": "SoDelicious.mp3", "volume": 0.5 },
    "뭐지": { "src": "WhatIsIT.mp3", "volume": 0.4 },
    "뭐야": { "src": "WhatIsThis.mp3", "volume": 0.4 },
    "돌핀": { "src": "Dolphin.mp3", "volume": 0.5 },
    "우쇼": { "src": "Usho.mp3", "volume": 0.5 },

    // [New Additions 2026-01-27]
    "아메리칸": { "src": "Crysis_Amercans.mp3", "volume": 0.3 },
    "남자답게": { "src": "Crysis_Be_A_Man.mp3", "volume": 0.3 },
    "못숨지": { "src": "Crysis_Cant_Hide.mp3", "volume": 0.3 },
    "찾을거야": { "src": "Crysis_Find.mp3", "volume": 0.3 },
    "다이": { "src": "DieYouSOB.mp3", "volume": 0.3 },
    "죽었어": { "src": "Crysis_death.mp3", "volume": 0.3 },
    "최고야": { "src": "AreYouBest.mp3", "volume": 0.4 },
    "다메난데": { "src": "Damenandesu.mp3", "volume": 0.5 },
    "하지마이": { "src": "Don'tDoIt.mp3", "volume": 0.4 },
    "피버": { "src": "Fever.mp3", "volume": 0.4 },
    "꼼짝": { "src": "Frozen.mp3", "volume": 0.3 },
    "간드아": { "src": "Ganda.mp3", "volume": 0.4 },
    "하야이": { "src": "Hayay.mp3", "volume": 0.4 },
    "헉": { "src": "Huk.mp3", "volume": 0.8 },
    "흡": { "src": "Hup.mp3", "volume": 0.5 },
    "자기생각": { "src": "Life3.mp3", "volume": 0.3 },
    "그래서재미": { "src": "Life4.mp3", "volume": 0.3 },
    "인생이란": { "src": "Life_is.mp3", "volume": 0.3 },
    "사랑해요": { "src": "LoveYou.mp3", "volume": 0.5 },
    "메이플": { "src": "Maple.mp3", "volume": 0.4 },
    "오케이": [
        { "src": "Okay.mp3", "volume": 0.5 },
        { "src": "Okey1.mp3", "volume": 0.5 }
    ],
    "오네가이": { "src": "OnegaySimasu.mp3", "volume": 0.5 },
    "헐떡": { "src": "Panting.mp3", "volume": 0.8 },
    "꿀떡": { "src": "Swallow.mp3", "volume": 0.8 },
    "섹": { "src": "Sax.mp3", "volume": 0.6 },
    "재밌잖아": { "src": "SoFun.mp3", "volume": 0.3 },
    "트리스트람": { "src": "Stay_awhile.mp3", "volume": 0.35 },
    "난재밌어": { "src": "ToMeIt'sSoFun.mp3", "volume": 0.3 },
    "회전회오리": { "src": "Tornado.mp3", "volume": 0.4 },
    "와츄고나두": { "src": "WaChuGoNaDo.mp3", "volume": 0.45 },
    "꺄악": { "src": "Whilhelm.mp3", "volume": 0.4 },
    "USB": { "src": "Windows 10 USB Disconnect.mp3", "volume": 0.5 },
    "예야": { "src": "Yaeya.mp3", "volume": 0.3 },
    "아앙": { "src": "aang.mp3", "volume": 0.65 },
    "고자라니": { "src": "gozarani1.mp3", "volume": 0.3 },
    "몬소리": [
        { "src": "mon_sound2.mp3", "volume": 0.2 },
        { "src": "mon_sound3.mp3", "volume": 0.2 },
        { "src": "mon_sound1.mp3", "volume": 0.2 },
    ],
    "난테네": { "src": "nantene.mp3", "volume": 0.5 },
    "썸씽": { "src": "SomeThingOnYourMind.mp3", "volume": 0.5 },
    "예압": { "src": "Yeap.mp3", "volume": 0.5 },
    "뭐였지": [
        { "src": "what_was_it.mp3", "volume": 0.2 },
        { "src": "what_was_it2.mp3", "volume": 0.2 },
        { "src": "what_was_it_3.mp3", "volume": 0.2 }],

    // [New Additions 2026-01-31]
    "인정해": { "src": "AdmitIt.mp3", "volume": 0.5 },
    "짜증났어": { "src": "AreYouAnnoyed.mp3", "volume": 0.5 },
    "여친있어요?": { "src": "AreYouSingle.mp3", "volume": 0.5 },
    "공습경보": [
        { "src": "Defcon1.mp3", "volume": 0.5 },
        { "src": "Defcon2.mp3", "volume": 0.5 }],
    "인성문제": { "src": "DoYouHavePersonalityProblem.mp3", "volume": 0.5 },
    "명령하지마라": { "src": "DontGiveMeOrders.mp3", "volume": 0.5 },
    "없어요": [
        { "src": "DontHaveOne.mp3", "volume": 0.5 },
        { "src": "DontHaveOne2.mp3", "volume": 0.5 },
        { "src": "DontHaveOne3.mp3", "volume": 0.5 }
    ],
    "머리부터 발끝": [
        { "src": "FromHeadToToe.mp3", "volume": 0.5 },
        { "src": "FromHeadToToe2.mp3", "volume": 0.5 }
    ],
    "훼이크다": { "src": "ItsFakeYouFools.mp3", "volume": 0.5 },
    "코와이네": { "src": "KoWaYiNe.mp3", "volume": 0.5 },
    "안때려": { "src": "NopeIWontHit.mp3", "volume": 0.5 },
    "나만아니면": { "src": "NotMe.mp3", "volume": 0.5 },
    "냥냥": { "src": "NyangNyang.mp3", "volume": 0.5 },
    "얼마나 처먹": { "src": "Pig1.mp3", "volume": 0.5 },
    "돼지같은": { "src": "YouArePig.mp3", "volume": 0.5 },
    "사사게오": [
        { "src": "ShinZoSaSaGeO.mp3", "volume": 0.5 },
        { "src": "ShinZoSaSaGeO2.mp3", "volume": 0.5 },
        { "src": "ShinZoSaSaGeO3.mp3", "volume": 0.5 }
    ],
    "앉아": [
        { "src": "SitDown.mp3", "volume": 0.5 },
        { "src": "SitDown2.mp3", "volume": 0.5 },
        { "src": "SitDown3.mp3", "volume": 0.5 },
        { "src": "SitDown4.mp3", "volume": 0.5 }
    ],
    "무서워라": { "src": "SoScary.mp3", "volume": 0.5 },
    "선오브비치": { "src": "SonOfBitch.mp3", "volume": 0.5 },
    "일어서": { "src": "StandUp.mp3", "volume": 0.5 },
    "나가": { "src": "SunFlower-GetOut.mp3", "volume": 0.5 },
    "왜태식이": { "src": "SunFlower-OhMrOh.mp3", "volume": 0.5 },
    "고맙다": { "src": "SunFlower-Thanks.mp3", "volume": 0.5 },
    "저 븅신": { "src": "SunFlower-ThatRetard.mp3", "volume": 0.5 },
    "이건기회야": { "src": "SunFlower-ThisIsMyMoment.mp3", "volume": 0.5 },
    "누가재수없게": { "src": "SunFlower-WhosCrying.mp3", "volume": 0.5 },
    "돌아왔구나": { "src": "SunFlower-YouBack.mp3", "volume": 0.5 },
    "후련했냐": { "src": "SunFlower-areYouSatisfied.mp3", "volume": 0.5 },
    "이안에": { "src": "ThereArePeopleInThere.mp3", "volume": 0.5 },
    "함정": { "src": "TrapBGM.mp3", "volume": 0.5 },
    "후아유": { "src": "WhoAreYou.mp3", "volume": 0.5 },
    "누구야": { "src": "WhoAreYou1.mp3", "volume": 0.5 },
    "누구인가": { "src": "WhoWasIt.mp3", "volume": 0.5 },
    "뭐야": { "src": "WTFareYou.mp3", "volume": 0.5 },
    "기침": { "src": "WhoJustCoughed.mp3", "volume": 0.5 },
    "와!샌즈": [
        { "src": "WaSands1.mp3", "volume": 0.5 },
        { "src": "WaSands2.mp3", "volume": 0.5 },
        { "src": "WaSands3.mp3", "volume": 0.5 },
        { "src": "WaSands4.mp3", "volume": 0.5 },
        { "src": "WaSandsWin.mp3", "volume": 0.5 }
    ],
    "왜나만": { "src": "WhyJustMe.mp3", "volume": 0.5 },
    "시발": [
        { "src": "Yabal1.mp3", "volume": 0.5 },
        { "src": "Yabal2.mp3", "volume": 0.5 },
        { "src": "YabalFolks2.mp3", "volume": 0.5 },
        { "src": "YabalFolks4.mp3", "volume": 0.5 }
    ],
    "뉴스도안보냐": { "src": "YouDontWatchNews.mp3", "volume": 0.5 },
    "티비도안보냐": { "src": "YouDontWatchTV.mp3", "volume": 0.5 },
    "꽁꽁": { "src": "itsFrozen.mp3", "volume": 0.5 },

    // [Batch 2 Additions]
    "같이밥묵고": { "src": "같이밥묵고.mp3", "volume": 0.5 },
    "그년한태": { "src": "그년한태.mp3", "volume": 0.5 },
    "그땐몰랐어": { "src": "그땐몰랐어.mp3", "volume": 0.5 },
    "남자가지고싶다": { "src": "남자가지고싶다.mp3", "volume": 0.5 },
    "내가": { "src": "내가!.mp3", "volume": 0.5 },
    "누구냐너": { "src": "누구냐너.mp3", "volume": 0.5 },
    "다했어": { "src": "다했어.mp3", "volume": 0.5 },
    "달콤한꿈": { "src": "달콤한꿈.mp3", "volume": 0.5 },
    "따라란": { "src": "따라란.mp3", "volume": 0.5 },
    "먹고살기힘들다": { "src": "먹고살기힘들다.mp3", "volume": 0.5 },
    "모욕감": { "src": "모욕감.mp3", "volume": 0.5 },
    "사쿠라야?": { "src": "사쿠라야.mp3", "volume": 0.5 },
    "소리가달라": { "src": "소리가달라.mp3", "volume": 0.5 },
    "쏠수있어": { "src": "쏠수있어1.mp3", "volume": 0.5 },
    "아예": { "src": "아예.mp3", "volume": 0.5 },
    "아주유명한": { "src": "아주유명한.mp3", "volume": 0.5 },
    "약을팔어": { "src": "약을팔어.mp3", "volume": 0.5 },
    "어데최씨": { "src": "어데최씨.mp3", "volume": 0.5 },
    "어저께도": { "src": "어저께도.mp3", "volume": 0.5 },
    "에?": [
        { "src": "에에.mp3", "volume": 0.5 },
        { "src": "에에2.mp3", "volume": 0.5 },
        { "src": "에에3.mp3", "volume": 0.5 },
        { "src": "에에4.mp3", "volume": 0.5 },
        { "src": "에에5.mp3", "volume": 0.5 },
        { "src": "에에6.mp3", "volume": 0.5 },
        { "src": "에에7.mp3", "volume": 0.5 },
        { "src": "에에8.mp3", "volume": 0.5 }
    ],
    "예쁜칼": { "src": "예쁜칼.mp3", "volume": 0.5 },
    "왜자르지않": { "src": "왜자르지않.mp3", "volume": 0.5 },
    "이대구빡이": { "src": "이대구빡이.mp3", "volume": 0.5 },
    "인생꼬": { "src": "인생꼬.mp3", "volume": 0.5 },
    "임마": { "src": "임마.mp3", "volume": 0.5 },
    "잘르라": { "src": "잘르라.mp3", "volume": 0.5 },
    "좋은날이있": { "src": "좋은날이있.mp3", "volume": 0.5 },
    "죽을죄": { "src": "죽을죄.mp3", "volume": 0.5 },
    "팬티를": { "src": "팬티를.mp3", "volume": 0.5 },
    "혓바닥이": { "src": "혓바닥이.mp3", "volume": 0.5 },
    "확인들어": { "src": "확인들어가.mp3", "volume": 0.5 },
    "후달리냐": { "src": "후달리냐.mp3", "volume": 0.5 },
    "삿갓": { "src": "삿갓.mp3", "volume": 0.5 },

    // [Auto-Discovered]
    "존나몬창": { "src": "Johnna MC.mp3", "volume": 0.2 },
    "잉곳": { "src": "ingot.mp3", "volume": 0.5 },
    "잉기잇": { "src": "ingit.mp3", "volume": 0.5 },
    "네전태": { "src": "OKLS.mp3", "volume": 0.5 },
    "끼야": { "src": "Screem.mp3", "volume": 0.5 },
    "이상한데수": { "src": "weird.mp3", "volume": 0.5 },
    "이왜대발": { "src": "whydps.mp3", "volume": 0.5 },
};

window.HIVE_VISUAL_CONFIG = {
    "해골": "skull",
    "커플": "couple",
    "하트": "heart",
    "버질": "vergil",
    "돌핀": "dolphin",
    "우쇼": "usho"
};
