// [Config Logic] Centralized Configuration for BubbleChat
// You can manually edit this file or overwrite it using the Export function in config.html
// AI Should Not Change Any Mapping that is already present
window.CHZZK_CHANNEL_ID = "057a9a03fea9b368eb0c76b9e95e1ae5"; // [Optional] Set your Channel ID here to skip lookup


// [Startup Configuration]
window.RANDOM_NAMES = [
    "섹시한누나", "도도한고양이", "여신이영", "체리입술", "밤의여왕", "앙큼한여우", "슬픈눈동자", "새벽이슬", "달콤한키스", "장미가시",
    "매혹적인그녀", "눈웃음작렬", "설레는마음", "그대만의연인", "사랑스러운걸", "팜므파탈", "청순글래머", "베이글녀", "섹시다이너마이트", "요염한자태"
];

window.WELCOME_MESSAGES = [
    // [Text Filters - Sexy/Pink]
    "!ㅜㅑ 오빠... 오늘 왜 이렇게 멋있어? 헤으응...",
    "!ㅜㅑ 나 오늘 속옷 안 입었는데... 궁금해? ㅎ",
    "!ㅜㅑ 자기야, 이리 와서 나 좀 안아줘...",

    // [Animations - Dance/Motion]
    "!둠칫둠칫 오빠랑 같이 춤추고 싶다! 신나게 흔들어봐~",
    "!둠칫둠칫 오늘 기분 최고야! 오빠도 같이 즐겨! 쪽쪽💋",
    "(( 자기야 나랑 같이 흔들어볼까? 쉐킷쉐킷 ))",
    ")) 오빠 엉덩이 춤 잘 춰? 나 꼬시는 거야? ((",
    "(( 이 리듬에 몸을 맡겨봐... 뜨겁게 ))",
    "~ 오빠... 나 어지러워... 잡아줘잉 ~",
    "~ 기분이 몽글몽글... 구름 위를 걷는 것 같아 ~",
    "~ 살랑살랑... 내 마음이 오빠한테 불어가네 ~",
    "~ 아잉 몰라몰라... 부끄럽단 말이야 ~",
    "~ 오빠 품에 안겨서 둥둥 떠다니고 싶어 ~",

    // [Animations - Reactions]
    "헤으응... 오빠 눈빛이 너무 강렬해... 숨 막혀",
    "헤으응... 나 오늘 좀 이상해... 열이 나는 것 같아",
    "헤으응... 자꾸 그렇게 쳐다보면 나 녹아버려...",
    "압축! 오빠랑 나랑 딱 붙어서 안 떨어질래!",
    "조이고! 오빠 내 마음 꽉 잡아줘! 놓치면 안 돼!",
    "자라나라! 우리 사랑도 쑥쑥 커져라 얍! 🌱",
    "히오스! 오빠의 매력이라는 소용돌이에 빨려든다!",
    "짜잔! 오빠의 영원한 아이돌 등장! 사랑해요!",
    "나죽어! 오빠 때문에 심쿵사 할 것 같아 ㅠㅠ 책임져!",
    "나죽어! 진짜 너무 잘생긴 거 아니야? 반칙이야!",

    // [Animations - Dramatic]
    "!나락 오빠한테 빠져버렸어... 출구가 없어 나락간다~",
    "!나락 내 이성은 이미 끝났어... 본능만 남았어",
    "!극락 오빠 얼굴 보니까 여기가 바로 천국이네 극락왕생!",
    "!극락 아... 오빠랑 있으니까 세상 다 가진 기분이야",
    "!떡상 우리 주식도 사랑도 떡상 가즈아! 🔥",
    "!떡락 내 통장은 텅장인데 오빠 사랑은 꽉 찼네",
    "ㄷㄷ 오빠 화난 모습도 섹시하다... 나 좀 떨려 ㄷㄷ",
    "ㄷㄷ 오늘 오빠 눈빛이 맹수 같아... 잡아먹힐 것 같아 ㄷㄷ",
    "?? 오빠 지금 나 꼬시는 거야? 그런 거야? ??",
    "?? 내 마음 훔쳐간 도둑이 요기 있네? ??",

    // [Sound Triggers - Explicit Keywords]
    "쪽쪽쪽 💋 내 모닝 키스 받아라! 사랑해!",
    "사랑해요 오빠! 내 마음의 1순위는 언제나 오빠야",
    "최고야! 역시 우리 오빠가 세상에서 제일 멋져 👍",
    "맛있다... 오빠가 사준 밥이라 더 맛있는 것 같아 냠냠",
    "재밌어! 오빠랑 노는 게 제일 좋아! 시간 가는 줄 몰라",
    "자기생각 하느라 밤샜어... 다크서클 봐봐 힝",
    "아하앙~ 기분 좋은 하루 시작! 오빠도 화이팅!",
    "와우! 오빠 피지컬 실화야? 만져봐도 돼?",
    "오옷! 뭔가 좋은 일이 생길 것 같은 예감이 들어!",
    "멍청아! 내가 오빠 좋아하는 것도 모르는 바보 흥!",
    "야스! 오늘 밤은 오빠랑 끝까지 달리는 거야!",
    "가능! 오빠라면 뭐든지 다 가능해! 믿을게!",
    "ㅗㅜㅑ... 진짜 감당 안 되네... 매력 터진다",

    // [New Batch: Light/Dark Effects]
    "빛! 찬란한 빛이여, 오빠를 비추소서! ✨",
    "빛! 오늘따라 후광이 비치네? 눈부셔!",
    "빛! 내 인생의 빛과 소금... 바로 너야",
    "빛! 어둠을 몰아내는 정의의 사도 등장!",
    "빛! 반짝반짝 작은 별... 아니 큰 별이네!",
    "흑화... 내 안의 흑염룡이 날뛴다... 크큭...",
    "흑화... 어둠의 다크니스... 진정한 힘을 보여주마",
    "흑화... 건드리지 마라... 지금 기분 안 좋다",
    "흑화... 세상이 나를 등졌다... 복수할 거야",
    "흑화... 타락천사 강림... 날개를 펼쳐라",

    // [New Batch: Diverse Sound Triggers - Memes & Gaming]
    "와!샌즈 아시는구나! 겁.나.어.렵.습.니.다",
    "와!샌즈 파피루스도 좋아해? 녜헤헤!",
    "함정! 함정카드를 발동했다! 넌 이제 끝이야",
    "함정! 이불 밖은 위험해! 거긴 함정이야!",
    "코와이네~ 유치원생 짱구보다 더 무서운 원장님?",
    "코와이네~ 속도가... 빛의 속도로 차이구나",
    "머리부터 발끝까지 오로나민C~ 생기발랄!",
    "머리부터 발끝까지 사랑스러워~ 워어어~",
    "야스! 기분 째진다! 오늘 파티 각이다!",
    "야스! 소리 질러! 풋쳐핸썹!",
    "가즈아! 비트코인 1억 가즈아! 화성 갈끄니까!",
    "가즈아! 오늘 저녁은 치킨이다! 달려!",
    "멈춰! 학교폭력 멈춰! 사랑으로 감싸줘요",
    "멈춰! 거기 너! 내 마음 훔쳐간 도둑!",
    "탈출! 지능순 탈출은 과학이다... 돔황챠!",
    "탈출! 비상 탈출 버튼을 눌러라! 삐용삐용",
    "인정해! 쿨하게 인정하면 멋진 사람이지",
    "인정해! 너도 사실 나 좋아하잖아? 다 알아",
    "짜증났어! 흥! 나 삐졌어 달래줘",
    "짜증났어! 왜 내 맘을 몰라주는 거야 바보",
    "실례합니다! 지나가겠습니다~ 비켜주세요~",
    "실례합니다! 마음 좀 훔치겠습니다~ 숑!",
    "수레! 아이고 나 죽네~ 수레 탄다~",
    "수레! 퀘스트 실패... 다시 도전 가자!",
    "나락! 으아아아 떨어진다! 잡아줘!",
    "나락! 민심 나락... 떡상 기원 1일차",
    "극락! 여기가 천국인가요? 눈호강 제대로 하네",
    "극락! 귀르가즘... 목소리 너무 좋아",
    "떡상! 존버는 승리한다! 떡상 가자!",
    "떡상! 오늘 텐션 미쳤다! 주체할 수 없어!",
    "안돼! 그런 짓은 하지 마라~ 후회할 거야",
    "안돼! 가지 마... 나 두고 가지 마 ㅠㅠ",
    "꺼져! 내 앞에서 사라져! (농담인 거 알지?)",
    "꺼져! 부정적인 생각은 저리 가라~ 훠이훠이",
    "헬로! 안녕? 반가워요! (영어 좀 하는 척)",
    "헬로! 마이 프렌드! 웰컴 투 마이 월드",
    "바이! 다음에 또 봐요! 아쉽지만 안녕",
    "바이! 쿨하게 떠나줄게... 잘 살아라",
    "운동! 오늘 헬스장 가는 날! 득근득근",
    "운동! 숨쉬기 운동도 운동이라고!",
    "유격! 유격 자신! 8번 올빼미 도하 준비 끝!",
    "유격! PT 체조 시작! 하나 둘 셋 넷!",
    "일어나! 아침 해가 떴습니다~ 자리에서 일어나!",
    "일어나! 언제까지 잘 거야? 잠꾸러기!",
    "뭐임? 이게 무슨 상황이야? 설명 좀",
    "뭐임? 갑자기 분위기 싸해지는데?",
    "마이쩡! 냠냠 쩝쩝... 너무 맛있다",
    "마이쩡! 세상에서 제일 행복한 맛이야",
    "기침! 콜록콜록... 감기 조심하세요",
    "기침! 에취! 누가 내 욕하나?",
    "시발! 아이고 깜짝이야! 욕 나올 뻔 했네",
    "시발! (시원한 바람이 부네~)",
    "뉴스도안보냐! 요즘 세상 돌아가는 것 좀 봐라",
    "티비도안보냐! 이거 완전 유행인데 모르면 간첩!",
    "꽁꽁! 얼어붙은 한강 위로 고양이가 걸어다닙니다",
    "꽁꽁! 내 마음이 얼어버렸어... 녹여줘",

    // [New Batch: Diverse Sound Triggers - Memes & Gaming]
    "와!샌즈 아시는구나! 겁.나.어.렵.습.니.다",
    "와!샌즈 파피루스도 좋아해? 녜헤헤!",
    "함정! 함정카드를 발동했다! 넌 이제 끝이야",
    "함정! 이불 밖은 위험해! 거긴 함정이야!",
    "코와이네~ 유치원생 짱구보다 더 무서운 원장님?",
    "코와이네~ 속도가... 빛의 속도로 차이구나",
    "머리부터 발끝까지 오로나민C~ 생기발랄!",
    "머리부터 발끝까지 사랑스러워~ 워어어~",
    "야스! 기분 째진다! 오늘 파티 각이다!",
    "야스! 소리 질러! 풋쳐핸썹!",
    "가즈아! 비트코인 1억 가즈아! 화성 갈끄니까!",
    "가즈아! 오늘 저녁은 치킨이다! 달려!",
    "멈춰! 학교폭력 멈춰! 사랑으로 감싸줘요",
    "멈춰! 거기 너! 내 마음 훔쳐간 도둑!",
    "탈출! 지능순 탈출은 과학이다... 돔황챠!",
    "탈출! 비상 탈출 버튼을 눌러라! 삐용삐용",
    "인정해! 쿨하게 인정하면 멋진 사람이지",
    "인정해! 너도 사실 나 좋아하잖아? 다 알아",
    "짜증났어! 흥! 나 삐졌어 달래줘",
    "짜증났어! 왜 내 맘을 몰라주는 거야 바보",
    "실례합니다! 지나가겠습니다~ 비켜주세요~",
    "실례합니다! 마음 좀 훔치겠습니다~ 숑!",
    "수레! 아이고 나 죽네~ 수레 탄다~",
    "수레! 퀘스트 실패... 다시 도전 가자!",
    "나락! 으아아아 떨어진다! 잡아줘!",
    "나락! 민심 나락... 떡상 기원 1일차",
    "극락! 여기가 천국인가요? 눈호강 제대로 하네",
    "극락! 귀르가즘... 목소리 너무 좋아",
    "떡상! 존버는 승리한다! 떡상 가자!",
    "떡상! 오늘 텐션 미쳤다! 주체할 수 없어!",
    "안돼! 그런 짓은 하지 마라~ 후회할 거야",
    "안돼! 가지 마... 나 두고 가지 마 ㅠㅠ",
    "꺼져! 내 앞에서 사라져! (농담인 거 알지?)",
    "꺼져! 부정적인 생각은 저리 가라~ 훠이훠이",
    "헬로! 안녕? 반가워요! (영어 좀 하는 척)",
    "헬로! 마이 프렌드! 웰컴 투 마이 월드",
    "바이! 다음에 또 봐요! 아쉽지만 안녕",
    "바이! 쿨하게 떠나줄게... 잘 살아라",
    "운동! 오늘 헬스장 가는 날! 득근득근",
    "운동! 숨쉬기 운동도 운동이라고!",
    "유격! 유격 자신! 8번 올빼미 도하 준비 끝!",
    "유격! PT 체조 시작! 하나 둘 셋 넷!",
    "일어나! 아침 해가 떴습니다~ 자리에서 일어나!",
    "일어나! 언제까지 잘 거야? 잠꾸러기!",
    "뭐임? 이게 무슨 상황이야? 설명 좀",
    "뭐임? 갑자기 분위기 싸해지는데?",
    "마이쩡! 냠냠 쩝쩝... 너무 맛있다",
    "마이쩡! 세상에서 제일 행복한 맛이야",
    "기침! 콜록콜록... 감기 조심하세요",
    "기침! 에취! 누가 내 욕하나?",
    "시발! 아이고 깜짝이야! 욕 나올 뻔 했네",
    "시발! (시원한 바람이 부네~)",
    "뉴스도안보냐! 요즘 세상 돌아가는 것 좀 봐라",
    "티비도안보냐! 이거 완전 유행인데 모르면 간첩!",
    "꽁꽁! 얼어붙은 한강 위로 고양이가 걸어다닙니다",
    "꽁꽁! 내 마음이 얼어버렸어... 녹여줘"
];

window.HIVE_SOUND_CONFIG = {
    // [Screen Effects]
    "커플": { "src": "DieWithASmile.mp3", "volume": 0.5 },
    "버질": { "src": "I AM THE STORM.mp3", "volume": 0.5 },
    "돌핀": { "src": "Dolphin.mp3", "volume": 0.5 },
    "하트": { "src": "Heart.mp3", "volume": 0.5 },
    "우쇼": { "src": "Usho.mp3", "volume": 0.5 },

    "해골": [
        { "src": "skullmeme.mp3", "volume": 0.5 },
        { "src": "skullmeme2.mp3", "volume": 0.5 },
        { "src": "skullmeme3.mp3", "volume": 0.5 },
        { "src": "skullmeme4.mp3", "volume": 0.5 },
        { "src": "skullmeme6.mp3", "volume": 0.5 },
        { "src": "skullmeme8.mp3", "volume": 0.5 },
        { "src": "skullmeme9.mp3", "volume": 0.5 },
        { "src": "skullmeme10.mp3", "volume": 0.5 },
        { "src": "skullmeme11.mp3", "volume": 0.5 }
    ],
    "앙": { "src": "Ang.mp3", "volume": 0.5 },
    "재밌다": { "src": "Fun.wav", "volume": 0.4 },
    "당근": { "src": "Carrot.mp3", "volume": 0.4 },
    "알림": { "src": "Alarm.mp3", "volume": 0.4 },

    // [Reactions & Memes]
    "ㅋㅋ": [{ "src": "Laugh1.mp3", "volume": 0.5 },
    { "src": "Laugh2.mp3", "volume": 0.3 },
    { "src": "Laugh3.mp3", "volume": 0.6 },
    { "src": "Laugh6.mp3", "volume": 0.3 },
    { "src": "Laugh.mp3", "volume": 0.3 },
    { "src": "Laugh7.mp3", "volume": 0.3 },
    { "src": "Laugh8.mp3", "volume": 0.5 },
    { "src": "Laugh4.mp3", "volume": 0.15 },
    { "src": "Laugh10.mp3", "volume": 0.4 },
    { "src": "Laugh5.mp3", "volume": 0.3 }],

    "아항항": { "src": "Laugh3.mp3", "volume": 0.6 },
    "와우": { "src": "Wow.mp3", "volume": 0.5 },
    "오옷": { "src": "Ot.wav", "volume": 0.4 },
    "헤으응": { "src": "Careless.mp3", "volume": 0.4 },
    "아흐앙": { "src": "ahng.mp3", "volume": 0.5 },
    "아흐응": { "src": "ah5.mp3", "volume": 0.3 },
    "아흣": { "src": "ah2.mp3", "volume": 0.4 },
    "아하앙": { "src": "ah3.mp3", "volume": 0.4 },
    "하으앙": { "src": "ah4.mp3", "volume": 0.4 },
    "윽": { "src": "ast5.mp3", "volume": 0.5 },
    "야스": { "src": "Yas.mp3", "volume": 0.5 },
    "두둥탁": { "src": "ddt.mp3", "volume": 0.5 },
    "짜잔": { "src": "tadah.mp3", "volume": 0.45 },
    "???": { "src": "mystery.mp3", "volume": 0.45 },
    "브로": { "src": "Bruh.mp3", "volume": 0.45 },
    "도파민": { "src": "Dopamin.mp3", "volume": 0.45 },
    "FBI": { "src": "FBI.mp3", "volume": 0.5 },
    "으아아": { "src": "Half-falling.mp3", "volume": 0.5 },
    "놉": { "src": "Nope.mp3", "volume": 0.5 },
    "더러워": { "src": "dirty.mp3", "volume": 0.6 },
    "비둘기": { "src": "pigeon.mp3", "volume": 0.5 },
    "야!": { "src": "야.mp3", "volume": 0.5 },
    "와!": [
        { "src": "chant1.mp3", "volume": 0.45 },
        { "src": "chant2.mp3", "volume": 0.5 },
        { "src": "chant3.mp3", "volume": 0.5 }
    ],
    "우와": { "src": "OMG_Good.mp3", "volume": 0.5 },
    "맙소사": { "src": "OMG.mp3", "volume": 0.5 },
    "앙기모띠": { "src": "AngKiMoChi.mp3", "volume": 0.5 },
    "기모띠": { "src": "kimotee.mp3", "volume": 0.5 },
    "응원": [
        { "src": "Cheer.mp3", "volume": 0.5 },
        { "src": "Cheer2.mp3", "volume": 0.5 },
        { "src": "Cheer3.mp3", "volume": 0.5 },
        { "src": "Cheer4.mp3", "volume": 0.5 },
        { "src": "Cheer6.mp3", "volume": 0.5 },
        { "src": "Cheer7.mp3", "volume": 0.5 },
        { "src": "Cheer9.mp3", "volume": 0.5 },
        { "src": "Cheer10.mp3", "volume": 0.5 }
    ],
    "미국맛": { "src": "Disconnected.mp3", "volume": 0.5 },
    "개소리": [
        { "src": "DogShit.mp3", "volume": 0.6 },
        { "src": "DogShit2.mp3", "volume": 0.5 },
        { "src": "DogShit3.mp3", "volume": 0.6 }
    ],
    "두잇": [
        { "src": "Doit1.mp3", "volume": 0.5 },
        { "src": "Doit2.mp3", "volume": 0.5 }
    ],
    "망했": { "src": "Doomed.mp3", "volume": 0.5 },
    "내눈": [
        { "src": "MyEyes01.mp3", "volume": 0.4 },
        { "src": "MyEyes02.mp3", "volume": 0.4 },
        { "src": "MyEyes03.mp3", "volume": 0.4 }
    ],
    "쌍욕": [
        { "src": "Bitch.mp3", "volume": 0.4 },
        { "src": "Fuck.mp3", "volume": 0.4 },
        { "src": "SuchABitch.mp3", "volume": 0.4 }
    ],
    "히히": [
        { "src": "WickedLaugh1.mp3", "volume": 0.7 },
        { "src": "WickedLaugh2.mp3", "volume": 0.7 },
        { "src": "WickedLaugh3.mp3", "volume": 0.7 },
        { "src": "WickedLaugh4.mp3", "volume": 0.7 }
    ],
    "대박": { "src": "Wow10.mp3", "volume": 0.5 },
    "오오오": { "src": "Chant4.mp3", "volume": 0.35 },
    "호우": { "src": "SIU.mp3", "volume": 0.7 },
    "siu": { "src": "SIU.mp3", "volume": 0.7 },
    "끼얏호": { "src": "Yiaho.mp3", "volume": 0.30 },
    "홋치": { "src": "whip.mp3", "volume": 0.5 },
    "맛있다": { "src": "Mat.mp3", "volume": 0.5 },

    // [Negative / Refusal]
    "안돼": [
        { "src": "no (1).mp3", "volume": 0.5 },
        { "src": "No.mp3", "volume": 1 },
        { "src": "No2.mp3", "volume": 0.5 },
        { "src": "No3.mp3", "volume": 0.5 },
        { "src": "No6.mp3", "volume": 0.5 }
    ],
    "멈춰!": { "src": "Stop.mp3", "volume": 0.65 },
    "꺼져": { "src": "foff.mp3", "volume": 0.45 },
    "뚝": { "src": "DDuk.wav", "volume": 0.4 },
    "쇼크": { "src": "shocked-sound-effect.mp3", "volume": 0.3 },
    "스트레스": { "src": "StressNeeds.mp3", "volume": 0.4 },
    "어림 없": { "src": "NoWay.mp3", "volume": 0.5 },
    "어림없": { "src": "NoWay.mp3", "volume": 0.5 },
    "응 아니야": { "src": "K-Nope.mp3", "volume": 0.5 },
    "죽고 싶지 않": { "src": "Don'tWannaDie.mp3", "volume": 0.5 },
    "장비를 정지": { "src": "Half-Stop.mp3", "volume": 0.5 },
    "너무한": { "src": "TooHarsh.mp3", "volume": 0.65 },
    "안되잖아": { "src": "Half-not-working.mp3", "volume": 0.5 },
    "정지가 안돼": [
        { "src": "Half-not-working2.mp3", "volume": 0.5 },
        { "src": "half-not-working4.mp3", "volume": 0.5 }
    ],

    // [Situation / Alerts]
    "하이": [
        { "src": "Hi1.mp3", "volume": 0.3 },
        { "src": "Hi2.mp3", "volume": 0.3 },
        { "src": "Hi3.mp3", "volume": 0.3 }
    ],
    "안녕하세요": { "src": "Hello1.mp3", "volume": 0.5 },
    "헬로": { "src": "Hello2.mp3", "volume": 1 },
    "바이": { "src": "Bye.mp3", "volume": 0.8 },
    "안녕히": { "src": "FareWellEveryone.mp3", "volume": 0.5 },
    "카톡": { "src": "Katalk.wav", "volume": 0.5 },
    "전화": { "src": "Call.WAV", "volume": 0.5 },
    "보이스콜": { "src": "KakaoCall.mp3", "volume": 0.5 },
    "디코": { "src": "discord.mp3", "volume": 0.5 },
    "잠시후": { "src": "FUmomentsLater.mp3", "volume": 0.7 },
    "장실": { "src": "willBeRightBack.mp3", "volume": 0.35 },
    "부끝": { "src": "willBeRightBack.mp3", "volume": 0.35 },
    "수류탄": { "src": "FireInTheHole.mp3", "volume": 0.5 },
    "탈출": [
        { "src": "Escape.mp3", "volume": 0.5 },
        { "src": "Escape2.mp3", "volume": 0.5 },
        { "src": "Escape3.mp3", "volume": 0.5 },
        { "src": "Escape4.mp3", "volume": 0.5 }
    ],
    "튀어": { "src": "RUN.mp3", "volume": 0.5 },
    "시작": { "src": "Begin.mp3", "volume": 0.5 },
    "가자!": { "src": "LetsGo.mp3", "volume": 0.75 },
    "결제": { "src": "applepay.mp3", "volume": 0.7 },
    "예상대로": { "src": "Predict.mp3", "volume": 0.5 },
    "배운다": { "src": "Learing.mp3", "volume": 0.4 },
    "운동": { "src": "workouthard.mp3", "volume": 0.4 },
    "유격": { "src": "MohyungTower.mp3", "volume": 0.5 },
    "일어나": [
        { "src": "WakeUp1.mp3", "volume": 0.5 },
        { "src": "WakeUp2.mp3", "volume": 0.5 },
        { "src": "WakeUp3.mp3", "volume": 0.5 },
        { "src": "WakeUp4.mp3", "volume": 0.5 },
        { "src": "WakeUp6.mp3", "volume": 0.5 },
        { "src": "WakeUp7.mp3", "volume": 0.5 },
        { "src": "WakeUp8.mp3", "volume": 0.5 },
        { "src": "WakeUp9.mp3", "volume": 0.5 }
    ],
    "뭐임?": { "src": "WTF.mp3", "volume": 0.5 },
    "엥?": { "src": "Huh.mp3", "volume": 0.5 },
    "음?": { "src": "Huh.mp3", "volume": 0.5 },
    "뭣?": { "src": "Huh.mp3", "volume": 0.5 },
    "ㅔ?": { "src": "Huh.mp3", "volume": 0.5 },
    "ㅖ?": { "src": "Huh.mp3", "volume": 0.5 },
    "마인": { "src": "MineMine.mp3", "volume": 0.5 },
    "제꺼": { "src": "NowMine.mp3", "volume": 0.8 },
    "마이!": [
        { "src": "MineMine.mp3", "volume": 0.5 }
    ],
    "마이쩡": { "src": "SoDelicious.mp3", "volume": 0.5 },
    "마이쪙": { "src": "SoDelicious.mp3", "volume": 0.5 },
    "뭐지": { "src": "WhatIsIT.mp3", "volume": 0.4 },
    "뭐야": { "src": "WhatIsThis.mp3", "volume": 0.4 },

    // [New Additions 2026-01-27]
    "아메리칸": { "src": "Crysis_Amercans.mp3", "volume": 0.3 },
    "남자답게": { "src": "Crysis_Be_A_Man.mp3", "volume": 0.3 },
    "못숨지": { "src": "Crysis_Cant_Hide.mp3", "volume": 0.3 },
    "찾을거야": { "src": "Crysis_Find.mp3", "volume": 0.3 },
    "다이": { "src": "DieYouSOB.mp3", "volume": 0.3 },
    "죽었어": { "src": "Crysis_death.mp3", "volume": 0.3 },
    "최고야": { "src": "AreYouBest.mp3", "volume": 0.4 },
    "다메난데": { "src": "Damenandesu.mp3", "volume": 0.5 },
    "하지마이": { "src": "Don'tDoIt.mp3", "volume": 0.4 },
    "피버": { "src": "Fever.mp3", "volume": 0.4 },
    "꼼짝": { "src": "Frozen.mp3", "volume": 0.3 },
    "간드아": { "src": "Ganda.mp3", "volume": 0.4 },
    "하야이": { "src": "Hayay.mp3", "volume": 0.4 },
    "헉": { "src": "Huk.mp3", "volume": 0.8 },
    "흡": { "src": "Hup.mp3", "volume": 0.5 },
    "자기생각": { "src": "Life3.mp3", "volume": 0.3 },
    "그래서재미": { "src": "Life4.mp3", "volume": 0.3 },
    "인생이란": { "src": "Life_is.mp3", "volume": 0.3 },
    "사랑해요": { "src": "LoveYou.mp3", "volume": 0.5 },
    "메이플": { "src": "Maple.mp3", "volume": 0.4 },
    "오케이": [
        { "src": "Okay.mp3", "volume": 0.5 },
        { "src": "Okey1.mp3", "volume": 0.5 }
    ],
    "오네가이": { "src": "OnegaySimasu.mp3", "volume": 0.5 },
    "헐떡": { "src": "Panting.mp3", "volume": 0.8 },
    "꿀떡": { "src": "Swallow.mp3", "volume": 0.8 },
    "섹": { "src": "Sax.mp3", "volume": 0.6 },
    "재밌잖아": { "src": "SoFun.mp3", "volume": 0.3 },
    "트리스트람": { "src": "Stay_awhile.mp3", "volume": 0.35 },
    "난재밌어": { "src": "ToMeIt'sSoFun.mp3", "volume": 0.3 },
    "회전회오리": { "src": "Tornado.mp3", "volume": 0.4 },
    "와츄고나두": { "src": "WaChuGoNaDo.mp3", "volume": 0.45 },
    "꺄악": { "src": "Whilhelm.mp3", "volume": 0.4 },
    "USB": { "src": "Windows 10 USB Disconnect.mp3", "volume": 0.5 },
    "예야": { "src": "Yaeya.mp3", "volume": 0.3 },
    "아앙": { "src": "aang.mp3", "volume": 0.65 },
    "고자라니": { "src": "gozarani1.mp3", "volume": 0.3 },
    "몬소리": [
        { "src": "mon_sound2.mp3", "volume": 0.2 },
        { "src": "mon_sound3.mp3", "volume": 0.2 },
        { "src": "mon_sound1.mp3", "volume": 0.2 },
    ],
    "난테네": { "src": "nantene.mp3", "volume": 0.5 },
    "썸씽": { "src": "SomeThingOnYourMind.mp3", "volume": 0.5 },
    "예압": { "src": "Yeap.mp3", "volume": 0.5 },
    "뭐였지": [
        { "src": "what_was_it.mp3", "volume": 0.2 },
        { "src": "what_was_it2.mp3", "volume": 0.2 },
        { "src": "what_was_it_3.mp3", "volume": 0.2 }],

    // [New Additions 2026-01-31]
    "인정해": { "src": "AdmitIt.mp3", "volume": 0.3 },
    "짜증냈어": { "src": "AreYouAnnoyed.mp3", "volume": 0.4 },
    "여친있어요?": { "src": "AreYouSingle.mp3", "volume": 0.7 },
    "공습경보": [
        { "src": "Defcon1.mp3", "volume": 0.4 },
        { "src": "Defcon2.mp3", "volume": 0.4 }],
    "인성문제": { "src": "DoYouHavePersonalityProblem.mp3", "volume": 0.4 },
    "명령하지마라": { "src": "DontGiveMeOrders.mp3", "volume": 0.4 },
    "없어요": [
        { "src": "DontHaveOne.mp3", "volume": 0.5 },
        { "src": "DontHaveOne2.mp3", "volume": 0.5 },
        { "src": "DontHaveOne3.mp3", "volume": 0.5 }
    ],
    "머리부터 발끝": [
        { "src": "FromHeadToToe.mp3", "volume": 0.3 },
        { "src": "FromHeadToToe2.mp3", "volume": 0.3 }
    ],
    "훼이크다": { "src": "ItsFakeYouFools.mp3", "volume": 0.3 },
    "코와이네": { "src": "KoWaYiNe.mp3", "volume": 0.3 },
    "안때려": { "src": "NopeIWontHit.mp3", "volume": 0.5 },
    "나만아니면": { "src": "NotMe.mp3", "volume": 0.3 },
    "냥냥": { "src": "NyangNyang.mp3", "volume": 0.1 },
    "얼마나 처먹": { "src": "Pig1.mp3", "volume": 0.5 },
    "돼지같은": { "src": "YouArePig.mp3", "volume": 0.5 },
    "사사게오": [
        { "src": "ShinZoSaSaGeO.mp3", "volume": 0.5 },
        { "src": "ShinZoSaSaGeO2.mp3", "volume": 0.4 },
        { "src": "ShinZoSaSaGeO3.mp3", "volume": 0.5 }
    ],
    "앉아": [
        { "src": "SitDown.mp3", "volume": 0.3 },
        { "src": "SitDown2.mp3", "volume": 0.3 },
        { "src": "SitDown3.mp3", "volume": 0.3 },
        { "src": "SitDown4.mp3", "volume": 0.3 }
    ],
    "무서워라": { "src": "SoScary.mp3", "volume": 0.4 },
    "선오브비치": { "src": "SonOfBitch.mp3", "volume": 0.4 },
    "일어서": { "src": "StandUp.mp3", "volume": 0.3 },
    "나가 뒤지기": { "src": "SunFlower-GetOut.mp3", "volume": 0.5 },
    "오태식이": { "src": "SunFlower-OhMrOh.mp3", "volume": 0.5 },
    "고맙다": { "src": "SunFlower-Thanks.mp3", "volume": 0.7 },
    "저 븅신": { "src": "SunFlower-ThatRetard.mp3", "volume": 0.5 },
    "이건기회야": { "src": "SunFlower-ThisIsMyMoment.mp3", "volume": 0.5 },
    "재수없게울고": { "src": "SunFlower-WhosCrying.mp3", "volume": 0.5 },
    "돌아왔구나": { "src": "SunFlower-YouBack.mp3", "volume": 0.5 },
    "후련했냐": { "src": "SunFlower-areYouSatisfied.mp3", "volume": 0.4 },
    "안에사람": { "src": "ThereArePeopleInThere.mp3", "volume": 0.4 },
    "함정": { "src": "TrapBGM.mp3", "volume": 0.3 },
    "후아유": { "src": "WhoAreYou.mp3", "volume": 0.4 },
    "누구야": { "src": "WhoAreYou1.mp3", "volume": 0.4 },
    "누구인가": { "src": "WhoWasIt.mp3", "volume": 0.5 },
    "뭐야": { "src": "WTFareYou.mp3", "volume": 0.6 },
    "기침": { "src": "WhoJustCoughed.mp3", "volume": 0.4 },
    "와!샌즈": [
        { "src": "WaSands1.mp3", "volume": 0.4 },
        { "src": "WaSands2.mp3", "volume": 0.4 },
        { "src": "WaSands3.mp3", "volume": 0.4 },
        { "src": "WaSands4.mp3", "volume": 0.4 },
        { "src": "WaSandsWin.mp3", "volume": 0.4 }
    ],
    "왜나만": { "src": "WhyJustMe.mp3", "volume": 0.4 },
    "시발롬": [
        { "src": "Yabal1.mp3", "volume": 0.5 },
        { "src": "Yabal2.mp3", "volume": 0.5 },
        { "src": "YabalFolks2.mp3", "volume": 0.5 },
        { "src": "YabalFolks4.mp3", "volume": 0.5 }
    ],
    "뉴스도안": { "src": "YouDontWatchNews.mp3", "volume": 0.4 },
    "테레비도안": { "src": "YouDontWatchTV.mp3", "volume": 0.4 },
    "꽁꽁": { "src": "itsFrozen.mp3", "volume": 0.7 },

    // [Batch 2 Additions]
    "같이밥묵고": { "src": "같이밥묵고.mp3", "volume": 0.45 },
    "그년한태": { "src": "그년한태.mp3", "volume": 0.4 },
    "그땐몰랐어": { "src": "그땐몰랐어.mp3", "volume": 0.5 },
    "남자가지고싶다": { "src": "남자가지고싶다.mp3", "volume": 0.6 },
    "내가!": { "src": "내가!.mp3", "volume": 0.5 },
    "누구냐너": { "src": "누구냐너.mp3", "volume": 0.7 },
    "다했어": { "src": "다했어.mp3", "volume": 0.4 },
    "달콤한꿈": { "src": "달콤한꿈.mp3", "volume": 0.3 },
    "따라란": { "src": "따라란.mp3", "volume": 0.6 },
    "먹고살기힘": { "src": "먹고살기힘들다.mp3", "volume": 0.6 },
    "모욕감": { "src": "모욕감.mp3", "volume": 0.45 },
    "사쿠라야?": { "src": "사쿠라야.mp3", "volume": 0.6 },
    "소리가달라": { "src": "소리가달라.mp3", "volume": 0.5 },
    "쏠수있어": { "src": "쏠수있어1.mp3", "volume": 0.3 },
    "아예": { "src": "아예.mp3", "volume": 0.6 },
    "아주유명한": { "src": "아주유명한.mp3", "volume": 0.5 },
    "약을팔어": { "src": "약을팔어.mp3", "volume": 0.3 },
    "어데최씨": { "src": "어데최씨.mp3", "volume": 0.7 },
    "어저께도": { "src": "어저께도.mp3", "volume": 0.5 },
    "에?": [
        { "src": "에에.mp3", "volume": 0.5 },
        { "src": "에에2.mp3", "volume": 0.5 },
        { "src": "에에3.mp3", "volume": 0.5 },
        { "src": "에에4.mp3", "volume": 0.5 },
        { "src": "에에5.mp3", "volume": 0.5 },
        { "src": "에에6.mp3", "volume": 0.5 },
        { "src": "에에7.mp3", "volume": 0.5 },
        { "src": "에에8.mp3", "volume": 0.5 }
    ],
    "예쁜칼": { "src": "예쁜칼.mp3", "volume": 0.7 },
    "왜자르지않": { "src": "왜자르지않.mp3", "volume": 0.3 },
    "이대구빡이": { "src": "이대구빡이.mp3", "volume": 0.3 },
    "인생꼬": { "src": "인생꼬.mp3", "volume": 0.3 },
    "임마": { "src": "임마.mp3", "volume": 0.3 },
    "자르라": { "src": "잘르라.mp3", "volume": 0.7 },
    "좋은날이있": { "src": "좋은날이있.mp3", "volume": 0.4 },
    "죽을죄": { "src": "죽을죄.mp3", "volume": 0.5 },
    "팬티를": { "src": "팬티를.mp3", "volume": 0.7 },
    "혓바닥이": { "src": "혓바닥이.mp3", "volume": 0.5 },
    "확인들어": { "src": "확인들어가.mp3", "volume": 0.3 },
    "후달리냐": { "src": "후달리냐.mp3", "volume": 0.6 },
    "삿갓": { "src": "삿갓이요.mp3", "volume": 0.5 },

    // [Auto-Discovered]
    "존나몬창": { "src": "Johnna MC.mp3", "volume": 0.2 },
    "잉곳": { "src": "ingot.mp3", "volume": 0.5 },
    "잉기잇": { "src": "ingit.mp3", "volume": 0.5 },
    "네전태": { "src": "OKLS.mp3", "volume": 0.5 },
    "끼야": { "src": "Screem.mp3", "volume": 0.5 },
    "이상한데수": { "src": "weird.mp3", "volume": 0.5 },
    "이왜대발": { "src": "whydps.mp3", "volume": 0.5 },

    // [CMC음성]
    "알피엠": { "src": "5000알피엠.mp3", "volume": 0.5 },
    "발파루크입브금틀어주세요": { "src": "ValstraxVoiceCover.mp3", "volume": 0.5 },
    "가자부 FULL": { "src": "가자부 FULL.mp3", "volume": 0.5 },
    "가자부": [{ "src": "가자부1.mp3", "volume": 0.5 },
    { "src": "가자부2.mp3", "volume": 0.5 }],
    "가즈아": { "src": "가즈아.mp3", "volume": 0.5 },
    "갓겜": [{ "src": "갓겜0.mp3", "volume": 0.5 },
    { "src": "갓겜1.mp3", "volume": 0.5 }],
    "갓겜합시다": { "src": "갓겜합시다1.mp3", "volume": 0.5 },
    "갓겜합시다FULL": { "src": "갓겜합시다FULL.mp3", "volume": 0.5 },
    "개꿀잼": { "src": "개꿀잼.mp3", "volume": 0.5 },
    "개쓰래기게임": { "src": "개쓰래기게임.mp3", "volume": 0.5 },
    "게임이어렵 [vocals]": { "src": "게임이어렵 [vocals].mp3", "volume": 0.5 },
    "겜안분": { "src": "겜안분.mp3", "volume": 0.5 },
    "교미교미": [{ "src": "교미교미.mp3", "volume": 0.5 },
    { "src": "교미교미2.mp3", "volume": 0.5 },
    { "src": "교미교미3.mp3", "volume": 0.5 }],
    "구멍이두개": { "src": "구멍이두개.mp3", "volume": 0.5 },
    "국밥에말아": { "src": "국밥에말아.mp3", "volume": 0.5 },
    "그건싫": { "src": "그건싫.mp3", "volume": 0.5 },
    "그만하세요": { "src": "그만하세요.mp3", "volume": 0.5 },
    "그만하세요좀": { "src": "그만하세요좀.mp3", "volume": 0.5 },
    "근무나갈시간": { "src": "근무나갈시간.mp3", "volume": 0.5 },
    "기억도나지않는다": { "src": "기억도나지않는다.mp3", "volume": 0.5 },
    "기폭용항": { "src": "기폭용항.mp3", "volume": 0.5 },
    "꼬리에선": { "src": "꼬리에선.mp3", "volume": 0.5 },
    "꼬짤": { "src": "꼬짤.mp3", "volume": 0.5 },
    "나가!": { "src": "나가.mp3", "volume": 0.5 },
    "나는!": [{ "src": "나는!.mp3", "volume": 0.5 },
    { "src": "나는!2.mp3", "volume": 0.5 }],
    "나도!": { "src": "나도.mp3", "volume": 0.5 },
    "나이스": { "src": "나이스.mp3", "volume": 0.5 },
    "나이사": { "src": "나이스아.mp3", "volume": 0.5 },
    "너무하는거": { "src": "너무하는거2.mp3", "volume": 0.5 },
    "너무하시네": { "src": "너무하시네.mp3", "volume": 0.5 },
    "노벨상줘야": { "src": "노벨상줘야.mp3", "volume": 0.5 },
    "다메": { "src": "다메.mp3", "volume": 0.5 },
    "대검위태도": { "src": "대검위태도.mp3", "volume": 0.5 },
    "도킹": { "src": "도킹.mp3", "volume": 0.5 },
    "도킹당": { "src": "도킹당.mp3", "volume": 0.5 },
    "도킹좋": { "src": "도킹좋.mp3", "volume": 0.5 },
    "따사!": { "src": "따사.mp3", "volume": 0.5 },
    "뜨겁게해줄게": { "src": "뜨겁게해줄게.mp3", "volume": 0.5 },
    "랜스!": { "src": "랜스.mp3", "volume": 0.5 },
    "만져보고싶다": { "src": "만져보고싶다.mp3", "volume": 0.5 },
    "만져본지언제": { "src": "만져본지언제.mp3", "volume": 0.5 },
    "말도안돼": { "src": "말도안되.mp3", "volume": 0.5 },
    "모넌을꺼요": { "src": "모넌을꺼요.mp3", "volume": 0.5 },
    "몬허브": { "src": "몬허브.mp3", "volume": 0.5 },
    "문열어": { "src": "문열어.mp3", "volume": 0.5 },
    "물설산씨티풀버전틀어주세요": { "src": "물설산씨티.mp3", "volume": 0.5 },
    "뭐야!": { "src": "뭐야.mp3", "volume": 0.5 },
    "미나상곤니찌와": { "src": "미나상곤니찌와.mp3", "volume": 0.5 },
    "미않술": { "src": "미않술.mp3", "volume": 0.5 },
    "발차기!": { "src": "발차기.mp3", "volume": 0.5 },
    "배려해야": { "src": "배려해야.mp3", "volume": 0.5 },
    "사나이눈물": { "src": "사나이눈물.mp3", "volume": 0.5 },
    "세상사람다설산": { "src": "세상사람다설산.mp3", "volume": 0.5 },
    "수렵돈": { "src": "수렵돈.mp3", "volume": 0.5 },
    "몬창의왕풀버전틀어주세요": { "src": "아들아.mp3", "volume": 0.5 },
    "아따시": { "src": "아따시.mp3", "volume": 0.5 },
    "아따시고멘네": { "src": "아따시고멘네.mp3", "volume": 0.5 },
    "아몰랑기모찌": { "src": "아몰랑기모찌.mp3", "volume": 0.5 },
    "아빨리!": { "src": "아빨리.mp3", "volume": 0.5 },
    "아스아!": [{ "src": "아스아.mp3", "volume": 0.5 },
    { "src": "아스아2.mp3", "volume": 0.5 }],
    "아시벌개꿀잼": { "src": "아시벌개꿀잼.mp3", "volume": 0.5 },
    "아아!": { "src": "아아.mp3", "volume": 0.5 },
    "아악!": { "src": "아악.mp3", "volume": 0.5 },
    "아왜?": { "src": "아왜.mp3", "volume": 0.5 },
    "아이말도안돼": { "src": "아이말도안돼.mp3", "volume": 0.5 },
    "아이보": { "src": "아이보.mp3", "volume": 0.5 },
    "아잭스": { "src": "아잭스.mp3", "volume": 0.5 },
    "아~합시다": { "src": "아합시다.mp3", "volume": 0.5 },
    "안녕하세요오": { "src": "안녕하세요오.mp3", "volume": 0.5 },
    "안돼안돼": { "src": "안돼안돼.mp3", "volume": 0.5 },
    "앗!": { "src": "앗.mp3", "volume": 0.5 },
    "애널형": { "src": "애널형.mp3", "volume": 0.5 },
    "애널형이어폰": { "src": "애널형이어폰.mp3", "volume": 0.5 },
    "야이개새끼들아": { "src": "야이개새끼.mp3", "volume": 0.5 },
    "야이미친놈들아": { "src": "야이미친놈들아.mp3", "volume": 0.5 },
    "어?": [{ "src": "어.mp3", "volume": 0.5 },
    { "src": "어어.mp3", "volume": 0.5 }],
    "어그로끌어야지": { "src": "어그로끌어야지.mp3", "volume": 0.5 },
    "어디가냐": { "src": "어디가냐.mp3", "volume": 0.5 },
    "어예": { "src": "어예.mp3", "volume": 0.5 },
    "어쩌라구요": { "src": "어쩌라구요.mp3", "volume": 0.5 },
    "에예": [{ "src": "에에.mp3", "volume": 0.5 },
    { "src": "에에2.mp3", "volume": 0.5 },
    { "src": "에에3.mp3", "volume": 0.5 },
    { "src": "에에4.mp3", "volume": 0.5 },
    { "src": "에에5.mp3", "volume": 0.5 },
    { "src": "에에6.mp3", "volume": 0.5 },
    { "src": "에에7.mp3", "volume": 0.5 },
    { "src": "에에8.mp3", "volume": 0.5 }],
    "엿이나드셔": { "src": "엿이나드셔.mp3", "volume": 0.5 },
    "엿이나드셔~": { "src": "엿이나드셔2.mp3", "volume": 0.5 },
    "예스!": { "src": "예스.mp3", "volume": 0.5 },
    "오게이!": { "src": "오게이.mp3", "volume": 0.5 },
    "오겡끼데스까": { "src": "오겡끼데스까.mp3", "volume": 0.5 },
    "오늘은기분이": { "src": "오늘은기분이.mp3", "volume": 0.5 },
    "오니짱": { "src": "오니짱.mp3", "volume": 0.5 },
    "오예": [{ "src": "오예.mp3", "volume": 0.5 },
    { "src": "오예2.mp3", "volume": 0.5 },
    { "src": "오예3.mp3", "volume": 0.5 },
    { "src": "오우예.mp3", "volume": 0.5 }],
    "완투": { "src": "완투.mp3", "volume": 0.5 },
    "왜?": { "src": "왜.mp3", "volume": 0.5 },
    "왜나CMC는": { "src": "왜나CMC는.mp3", "volume": 0.5 },
    "왜왜": { "src": "왜왜.mp3", "volume": 0.5 },
    "외출한김에": { "src": "외출한김에.mp3", "volume": 0.5 },
    "욧샤": { "src": "욧샤.mp3", "volume": 0.5 },
    "용조종너무": { "src": "용조종너무.mp3", "volume": 0.5 },
    "위이": { "src": "위이.mp3", "volume": 0.5 },
    "응애": { "src": "응애.mp3", "volume": 0.5 },
    "이거실화야": { "src": "이거실화야.mp3", "volume": 0.5 },
    "이걸왜유투브": { "src": "이걸왜유투브.mp3", "volume": 0.5 },
    "이놈": { "src": "이놈.mp3", "volume": 0.5 },
    "이새낀건랜서": [{ "src": "이새낀건랜서.mp3", "volume": 0.5 },
    { "src": "이새낀건랜서2.mp3", "volume": 0.5 }],
    "이안에사람": { "src": "이안에사람2.mp3", "volume": 0.5 },
    "이해가안돼": { "src": "이해가안되.mp3", "volume": 0.5 },
    "인정해안해": { "src": "인정해안해3.mp3", "volume": 0.5 },
    "잠들어라": { "src": "잠들어라.mp3", "volume": 0.5 },
    "장난하지마": [{ "src": "장난하지마.mp3", "volume": 0.5 },
    { "src": "장난하지마2.mp3", "volume": 0.5 }],
    "조룡!": { "src": "조룡!.mp3", "volume": 0.5 },
    "존나재밌어": { "src": "존나재밌어.mp3", "volume": 0.5 },
    "지금문열어": { "src": "지금문열어.mp3", "volume": 0.5 },
    "지금하자": { "src": "지금하자.mp3", "volume": 0.5 },
    "최뱀": { "src": "최뱀1.mp3", "volume": 0.5 },
    "츠지모토상오하": { "src": "츠지모토상오하이오.mp3", "volume": 0.5 },
    "치욕스러워": { "src": "치욕스러워.mp3", "volume": 0.5 },
    "토끼경단풀버전틀어주세요": { "src": "토끼경단.mp3", "volume": 0.5 },
    "하하하": [{ "src": "하하하1.mp3", "volume": 0.5 },
    { "src": "하하하11.mp3", "volume": 0.5 },
    { "src": "하하하12.mp3", "volume": 0.5 },
    { "src": "하하하13.mp3", "volume": 0.5 },
    { "src": "하하하14.mp3", "volume": 0.5 },
    { "src": "하하하2.mp3", "volume": 0.5 },
    { "src": "하하하3.mp3", "volume": 0.5 },
    { "src": "하하하4.mp3", "volume": 0.5 },
    { "src": "하하하5.mp3", "volume": 0.5 },
    { "src": "하하하8.mp3", "volume": 0.5 },
    { "src": "하하하9.mp3", "volume": 0.5 }],
    "흔들리며산다": { "src": "흔들리며산다.mp3", "volume": 0.5 },
};

window.HIVE_VISUAL_CONFIG = {
    "해골": "skull",
    "커플": "couple",
    "하트": "heart",
    "버질": "vergil",
    "돌핀": "dolphin",
    "우쇼": "usho"
};
