const assert = require('assert');
const HuntLobbyRoster = require('../js/effects/hunt/HuntLobbyRoster.js');

const values = [0.2, 0.8, 0.1, 0.6, 0.4];
let cursor = 0;
const roster = new HuntLobbyRoster(() => values[cursor++ % values.length]);
const streamerRegistration = roster.register({ nickname: 'A', uid: 'streamer-id', isStreamer: true });
assert.strictEqual(streamerRegistration.added, true);
assert.strictEqual(streamerRegistration.participant.uid, 'streamer-id');
assert.strictEqual(streamerRegistration.participant.isStreamer, true);
assert.strictEqual(roster.register({ nickname: 'A' }).added, false);
const ownerAliasRoster = new HuntLobbyRoster(() => 0.5);
const ownerAlias = ownerAliasRoster.register({ nickname: ' 최마치 ', isStreamer: false });
assert.strictEqual(ownerAlias.participant.isStreamer, true, '최마치 must receive the owner-only CMC profile even if Chzzk omits its role flag');
const hiddenCharacterOwner = new HuntLobbyRoster(() => 0).register({ nickname: '\u200B최마치\uFEFF', isStreamer: false });
assert.strictEqual(hiddenCharacterOwner.participant.isStreamer, true, 'invisible relay characters must not hide the configured streamer nickname');
const literalCmc = ownerAliasRoster.register({ nickname: 'CMC', isStreamer: false });
assert.strictEqual(literalCmc.participant.isStreamer, false, 'the letters CMC are not a streamer identity');
['B', 'C', 'D', 'E', 'F'].forEach(nickname => roster.register({ nickname }));
const selected = roster.selectFour();
assert.strictEqual(selected.length, 4);
assert.strictEqual(new Set(selected.map(item => item.nickname)).size, 4);

const shortRoster = new HuntLobbyRoster(() => 0);
shortRoster.register({ nickname: '유저' });
const filled = shortRoster.selectFour();
assert.strictEqual(filled.length, 4);
assert.strictEqual(filled.filter(item => item.isNpc).length, 3);
assert.ok(filled.filter(item => item.isNpc).every(item => item.isStreamer === false && item.uid === null));
console.log('[test] Hunt unique recruitment and four-hunter selection passed.');
